# Generated by Django 4.1.4 on 2022-12-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0002_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(),
        ),
    ]
