# Generated by Django 4.0.3 on 2022-06-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_info',
        ),
    ]
