# Generated by Django 4.0.3 on 2022-06-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_student1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student1',
            table='student_info',
        ),
    ]
