# Generated by Django 4.0.3 on 2022-06-08 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_place_resturant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='place_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.place'),
        ),
    ]
