# Generated by Django 4.0.3 on 2022-06-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_person6_orderperson_alter_resturant_place_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPerson1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.person6', models.Model),
        ),
    ]
