# Generated by Django 4.0.3 on 2022-06-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_article_book_piece_bookreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_piece',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_piece',
        ),
    ]
