# Generated by Django 4.0.3 on 2022-06-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_article_article_piece_remove_book_book_piece'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
