# Generated by Django 4.0.3 on 2022-06-20 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('gift', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userscan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='event.event'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sub_events', to='event.subevent'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to='event.event'),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_event_attendance', to='event.subevent'),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventvoucher',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventvoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_vouchers', to='gift.voucher'),
        ),
        migrations.AddField(
            model_name='eventvoucher',
            name='voucher_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_option_events', to='gift.voucheroption'),
        ),
        migrations.AddField(
            model_name='eventspecialgift',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_gifts', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventspecialgift',
            name='special_gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_special', to='gift.specialgift'),
        ),
        migrations.AddField(
            model_name='eventqr',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='breakup_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_payments', to='event.paymentbreakup'),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='event_special_gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_gift_pyment', to='event.eventspecialgift'),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='event_vouchers',
            field=models.ManyToManyField(blank=True, null=True, related_name='evnet_voucher_payments', to='event.eventvoucher'),
        ),
        migrations.AddField(
            model_name='eventpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventimages',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventhost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventhost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventgreetings',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_greetings', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventgreetings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_greetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventgift',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_records', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventattendingqr',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attending_qr', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventattendingqr',
            name='sub_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_event_attending_qr', to='event.subevent'),
        ),
        migrations.AddField(
            model_name='event',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ty_events', to='event.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='linked_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_events', to='event.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='relation',
            field=models.ForeignKey(help_text='show us the relation of event creator', on_delete=django.db.models.deletion.CASCADE, related_name='rel_events', to='event.relation'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('user', 'event', 'sub_event')},
        ),
        migrations.AlterUniqueTogether(
            name='userattendance',
            unique_together={('user', 'event', 'sub_event')},
        ),
        migrations.AlterUniqueTogether(
            name='eventvoucher',
            unique_together={('event', 'voucher', 'voucher_option')},
        ),
        migrations.AlterUniqueTogether(
            name='eventspecialgift',
            unique_together={('event', 'special_gift')},
        ),
        migrations.AlterUniqueTogether(
            name='eventattendingqr',
            unique_together={('event', 'sub_event')},
        ),
    ]
